yarnPath: ".yarn/releases/yarn-4.4.0.cjs"
nodeLinker: pnp
# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#   - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#   - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#   - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs